### ISSUE TITLE
Color scheme for AcroBot output

### ISSUE THREAD

**Issue by soulcharmer** [eliskasl/AcroBot#6]
For example, using '<b>xyz</b>' seems like redundant formating

Propose a sober color scheme for the output, coloring the acronym, its expanded version and the flags differently

**Comment by eliskasl** [comment]
Tried and didn't like it. Closing for now.
If you come up with a color scheme that will actually work and look well in any IRC client, regardless of the theme it uses, feel free to send me a pull request.
